trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  inputs:
    key: '"$(Agent.OS)" | cargo | Cargo.toml'
    restoreKeys: '"$(Agent.OS)" | cargo | Cargo.toml'
    path: |
      ~/.cargo/registry
      ~/.cargo/git
      target
- script: bash ci/run_geckodriver.sh
- script: cargo run