name: run
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
    - run: cargo run
      # continue-on-error: true
