name: run
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
    - run: geckodriver &
    - run: |
      curl -H 'Content-Type: application/json' -d '{"capabilities": {"alwaysMatch": {"browserName": "firefox"}}}' http://localhost:4444/session
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
    - run: cargo run
      # continue-on-error: true
